language: python
python:
  - "3.5"
before_script:
  - wget https://bitbucket.org/pypy/pypy/downloads/pypy-4.0.0-linux64.tar.bz2 -O /tmp/pypy.tar.bz2
  - mkdir /tmp/pypy
  - tar -xvf /tmp/pypy.tar.bz2 -C /tmp/pypy --strip-components 1
  - bin/prepare_testing.sh
  - export PATH=/tmp/pypy/bin/:$PWD/prob/:$PATH

env:
  - TOX_ENV=pep8
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pypy
install:
  - pip install --upgrade pip setuptools tox virtualenv
matrix:
  allow_failures:
    - env: TOX_ENV=pep8
    - env: TOX_ENV=flake8
script:
  - tox -e $TOX_ENV
after_failure:
  - for X in .tox/$TOX_ENV/log/*; do echo "$X\n"; cat "$X"; echo "\n\n"; done
  - echo "pip.log\n"; cat $HOME/.pip/pip.log
sudo: false
